/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Production-ready helper to generate high quality PDF report templates HTML
export function generateCertifiedCandidateDossier(candidate) {
  const dateStr = new Date().toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata' });

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Aynkaran Consultants - Official Dossier</title>
      <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1E293B; margin: 40px; line-height: 1.5; }
        .header { border-bottom: 2px solid #2563EB; padding-bottom: 20px; margin-bottom: 30px; }
        .logo-text { font-size: 24px; font-weight: bold; color: #1E3A8A; text-transform: uppercase; letter-spacing: 1px; }
        .sublogo { font-size: 11px; color: #64748B; text-transform: uppercase; margin-top: 4px; letter-spacing: 2px; }
        .title { font-size: 18px; font-weight: bold; margin-top: 20px; color: #334155; }
        .meta-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .meta-table td { padding: 8px 12px; border: 1px solid #E2E8F0; font-size: 12px; }
        .meta-table td.label { font-weight: bold; background-color: #F8FAFC; width: 25%; }
        .section-header { font-size: 14px; font-weight: bold; border-bottom: 1px solid #CBD5E1; padding-bottom: 6px; margin: 30px 0 12px 0; color: #1E3A8A; }
        .history-list { font-size: 11px; margin-left: 15px; }
        .history-item { margin-bottom: 6px; }
        .footer { text-align: center; margin-top: 80px; font-size: 10px; color: #94A3B8; border-top: 1px solid #F1F5F9; padding-top: 15px; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo-text">Aynkaran Consultants Ltd</div>
        <div class="sublogo">Onboarding & Insurance Advisory ERP Portal</div>
      </div>

      <div class="title">TRAINEE CANDIDATE DOSSIER REPORT</div>
      <p style="font-size: 11px; color: #64748B;">Generated dynamically on: ${dateStr} (Office Record)</p>

      <table class="meta-table">
        <tr>
          <td class="label">Candidate ID</td>
          <td>${candidate.id}</td>
          <td class="label">Full Legal Name</td>
          <td>${candidate.name}</td>
        </tr>
        <tr>
          <td class="label">Mobile Number</td>
          <td>${candidate.mobile || 'N/A'}</td>
          <td class="label">Email Address</td>
          <td>${candidate.email || 'N/A'}</td>
        </tr>
        <tr>
          <td class="label">Current Stage</td>
          <td><strong style="color: #2563EB;">${candidate.currentStage}</strong></td>
          <td class="label">Appointment Date</td>
          <td>${candidate.appointmentDate || 'N/A'}</td>
        </tr>
        <tr>
          <td class="label">Exam Fee Paid</td>
          <td>${candidate.fees?.applicationFeePaid ? 'Rs. 150 (SUCCESS)' : 'PENDING'}</td>
          <td class="label">Training Fee Paid</td>
          <td>${candidate.fees?.trainingFeePaid ? 'Rs. 250 (SUCCESS)' : 'PENDING'}</td>
        </tr>
      </table>

      <div class="section-header">Candidate Registration Progress Logs</div>
      <ol class="history-list">
        ${candidate.stageHistory?.map(hist => `
          <li class="history-item">
            <strong>${hist.stage}</strong> - <span style="color: #64748B;">${hist.date}</span>
            ${hist.note ? `<br/><span style="color: #475569; font-style: italic;">Note: ${hist.note}</span>` : ''}
          </li>
        `).join('') || '<li>No stages logged.</li>'}
      </ol>

      <div class="section-header">IRDAI Certification Exams & Credentials</div>
      <table class="meta-table">
        <tr>
          <td class="label">Scheduled Date</td>
          <td>${candidate.exam?.scheduledDate || 'Not yet scheduled'}</td>
          <td class="label">Examination Score</td>
          <td>${candidate.exam?.score !== undefined ? `${candidate.exam.score}/50` : 'N/A'}</td>
        </tr>
        <tr>
          <td class="label">Exam Result Status</td>
          <td><strong style="color: ${candidate.exam?.result === 'Pass' ? '#16A34A' : '#DC2626'}">${candidate.exam?.result || 'Awaiting Result'}</strong></td>
          <td class="label">Allotted LIC Code</td>
          <td><strong>${candidate.exam?.agentCodeGenerated || 'Awaiting allotment'}</strong></td>
        </tr>
      </table>

      <div class="footer">
        Aynkaran Consultants Limited &bull; Regional LIC Career Agent Development Division<br/>
        Email: hr@aynkaranconsultants.com | Mobile: +91 94472 83011<br/>
        This dossier is generated by Aynkaran Desk CRM and is verified as accurate.
      </div>
    </body>
    </html>
  `;
}
